### ISSUE TITLE
Compilation error in recent version

### ISSUE THREAD

**Issue by gugahoa** [FormidableLabs/reason-urql#122]
https://github.com/FormidableLabs/reason-urql/blob/master/src/components/UrqlQuery.re#L71

`pause` should be changed to `?pause`
```
  69 ┆   variables
  70 ┆   requestPolicy={UrqlTypes.requestPolicyToJs(requestPolicy)}
  71 ┆   pause>
  72 ┆   {result => result |> urqlQueryResponseToReason(parse) |> children}
  73 ┆ </QueryJs>;

  This has type:
    option(bool)
  But somewhere wanted:
    bool
```

**Comment by gugahoa** [comment]
This is quite strange, I got this error when compiling a new project, after doing the changes I came back to try and fix this, but just noticed it should be exactly like this. :thinking: 

I'll further investigate this issue

**Comment by gugahoa** [comment]
Looks like a breaking change from bucklescript

**Comment by gugahoa** [comment]
Ok, this looks like both a bug in reason-urql and a breaking change on bucklescript. I found a fix that will work on bs-platform 5.2.1 and bs-platform 6.2.1
